### ISSUE TITLE
[DISCUSS] Introduce gawk to e2e-container

### ISSUE THREAD

**Issue by dmsolr** [SkyAPMTest/e2e-container#6]
I find it very common for us to use `gawk`, such as e2e-profile, e2e-ttl and e2e-cluster. Maybe we have more e2e using it. But we have to install it from the internet every time. So I think we can introduce the tools to e2e-container to avoid these operations(update repo, download and install).

P.S. These two images have the same size, it is 305MB.

**Comment by kezhenxu94** [comment]
feel free to open a PR if you need it
